version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfile.mysql 
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./database/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "./wait-for-it.sh db 3306 && npm start"]
    depends_on:
      - db
    ports:
      - "3000:3000"